APPLICATION = openwsn_sctimer
include ../Makefile.tests_common

USEPKG += openwsn
USEMODULE += at86rf2xx
USEMODULE += xtimer

CFLAGS += -DDEVELHELP
CFLAGS_OPT = -O0

include $(RIOTBASE)/Makefile.include
